In [1]:
import pandas as pd

df = pd.read_csv("food_delivery_data.csv")

df["PerformanceFlag"] = df["DeliveryTime"].apply(
    lambda x: "Delayed" if x > 60 else "On Time"
)

summary = df.groupby("Cuisine").agg(
    Total_Revenue=("Revenue", "sum"),
    AvgDeliveryTime=("DeliveryTime", "mean"),
    Order_Count=("OrderID", "count")
).reset_index()

with pd.ExcelWriter("food_delivery_summary.xlsx") as writer:
    summary.to_excel(writer, sheet_name="Summary", index=False)

summary

     Cuisine  Total_Revenue  AvgDeliveryTime  Order_Count
0    Chinese         1410.0            48.25            4
1  Fast Food         1155.0            50.25            4
2     Indian         2270.0            26.50            4
3    Italian         1950.0            44.75            4
4    Mexican         1160.0            48.25            4

In [2]:
#The AI-generated solution does not validate DeliveryTime values.
#It accepts the negative value -5 as a real delivery time, which can affect the average delivery time.
df[df["DeliveryTime"] < 0]

  OrderID Cuisine  DeliveryTime  Revenue PerformanceFlag
5   O4006  Indian            -5    500.0         On Time

In [3]:
import pandas as pd

df = pd.read_csv("food_delivery_data.csv")

# Remove invalid negative delivery times
df = df[df["DeliveryTime"] >= 0]

# Create PerformanceFlag
df["PerformanceFlag"] = df["DeliveryTime"].apply(
    lambda x: "Delayed" if x > 60 else "On Time"
)

summary = df.groupby("Cuisine").agg(
    Total_Revenue=("Revenue", "sum"),
    AvgDeliveryTime=("DeliveryTime", "mean"),
    Order_Count=("OrderID", "count")
).reset_index()

with pd.ExcelWriter("food_delivery_summary.xlsx") as writer:
    summary.to_excel(writer, sheet_name="Summary", index=False)

summary

     Cuisine  Total_Revenue  AvgDeliveryTime  Order_Count
0    Chinese         1410.0            48.25            4
1  Fast Food         1155.0            50.25            4
2     Indian         1770.0            37.00            3
3    Italian         1950.0            44.75            4
4    Mexican         1160.0            48.25            4

The AI-generated code did not check whether the DeliveryTime values were valid. My dataset contained a DeliveryTime of -5, which is not possible and could affect the average delivery time. I found this issue by checking the negative values in the dataset. I manually fixed it by removing records where DeliveryTime was less than 0 before creating the summary.